services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SoftPassio\UserBundle\Doctrine\UserManager:
        public: true
        arguments:
            $className: '%soft_passio_app_user.entities.user_class%'
        calls:
            - method: setEncoder
              arguments:
                  - '@security.password_encoder'
